from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

from glob import glob
brain_samples = [os.path.basename(folder) for folder in glob(os.path.join('data/original/ST/visium_data_{0}/'.format('brain'), '*'))]
heart_samples = [os.path.basename(folder) for folder in glob(os.path.join('data/original/ST/visium_data_{0}/'.format('heart'), '*'))]
rule all:
    input:
        expand('data/working/ST/Misty/brain/{sample}/{view_type}_misty_model', sample = brain_samples, view_type = ['functional','celltype']),
        expand('data/working/ST/Misty/brain/{sample}/functional_misty_model', sample = heart_samples)


module general:
    snakefile: "rules/general.smk"
    config: config

use rule * from general

module celloracle:
    snakefile: "rules/celloracle.smk"
    config: config

use rule * from celloracle

module preprocessing:
    snakefile: "rules/preprocessing.smk"
    config: config

use rule * from preprocessing as PP_*

module functional:
    snakefile: "rules/functional.smk"
    config: config

use rule * from functional as fun_*

module misty:
    snakefile: "rules/misty.smk"
    config: config

use rule * from misty as misty_*

# snakemake --profile config/slurm/ celloracle
# conda env update --file local.yml --prune
