from snakemake.utils import min_version
min_version("6.0")

configfile: "config/config.yaml"

module general:
    snakefile: "rules/general.smk"
    config: config

use rule * from general

module celloracle:
    snakefile: "rules/celloracle.smk"
    config: config

use rule * from celloracle

module preprocessing:
    snakefile: "rules/preprocessing.smk"
    config: config

use rule * from preprocessing as PP_*

module functional:
    snakefile: "rules/functional.smk"
    config: config

use rule * from functional as fun_*

module misty:
    snakefile: "rules/misty.smk"
    config: config

use rule * from misty as misty_*

# snakemake --profile config/slurm/ celloracle
# conda env update --file local.yml --prune
