restart-times: 0
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py"
cluster-status: "slurm-status.py"
cluster-cancel: "scancel"
max-jobs-per-second: 1
max-status-checks-per-second: 10
local-cores: 16
latency-wait: 60
use-conda: True
use-envmodules: True
jobs: 1
default-resources:
    - runtime=14400
    - mem_mb=16000
