# Datasets
neurips2021:
    organism: "human"
    data: "https://www.ncbi.nlm.nih.gov/geo/download/?acc=GSE194122&format=file&file=GSE194122%5Fopenproblems%5Fneurips2021%5Fmultiome%5FBMMC%5Fprocessed%2Eh5ad%2Egz"
    trajectories:
        blood:
            celltypes: 'HSC;MKE_prog;Proerythroblast;Erythroblast;Normoblast'
            celloracle:
                min_count: 2000
                max_count: 15000
                thr_coaccess: 0.8
                fpr: 0.02
                thr_motif_score: 10
                thr_edge_pval: 0.001
                thr_top_edges: 2000

samples:
    brain: ['Sample_159_B1', 'Sample_159_A1', 'Sample_158_A1', 'Sample_158_B1', 'Sample_304_B1', 'Sample_304_A1', 'Sample_159_D1', 'Sample_158_D1', 'Sample_304_C1', 'Sample_158_C1', 'Sample_304_D1', 'Sample_159_C1']
    heart: ['V19T26_107_A1_G9', 'V19L29_043_A1_G7', 'V19T26_107_B1_G9', 'V19L29_045_A1_G7', 'V19L29_045_B1_G7', 'V19L29_047_A1_G7', 'V19T26_017_C1_F9', 'V19T26_108_C1_F9', 'V19L29_044_B1_G7', 'V19T26_017_D1_F9', 'V19L29_046_A1_G7', 'V19L29_044_A1_G7', 'V19T26_108_D1_F9', 'V19L29_046_B1_G7', 'V19T26_016_C1_F2', 'V19L29_046_C1_F1', 'V19T26_014_C1_F2', 'V19T26_015_A1_G8', 'V19T26_108_B1_G9', 'V19T26_016_D1_F2', 'V19T26_017_A1_G9', 'V19T26_015_B1_G8', 'V19T26_108_A1_G9', 'V19T26_014_D1_F2', 'V19T26_017_B1_G9', 'V19L29_046_D1_F1', 'V19L29_047_C1_F1', 'V19T26_107_D1_F9', 'V19T26_015_C1_F2', 'V19L29_047_B1_F1', 'V19L29_043_D1_F1', 'V19L29_045_C1_F1', 'V19T26_014_B1_G8', 'V19T26_016_A1_G8', 'V19T26_107_C1_F9', 'V19T26_015_D1_F2', 'V19L29_047_D1_F1', 'V19L29_045_D1_F1', 'V19T26_014_A1_G8', 'V19L29_043_C1_F1', 'V19T26_016_B1_G8']

deconvolution:
    assay: 'hvg2000'

functional:
    normalisation: 'log1p' #or SCT
    pathways_top_gene: 300
    pathways_method: 'mlm'

misty:
    random_seed: 42
    functional:
        bypass_intra: True
        plots:
            brain: {'trim': 2, 'cutoff': 1.5}
            heart: {'trim': 2, 'cutoff': 1.5}
    pathwaysCT:
        bypass_intra: True
        plots:
            brain: {'trim': 2, 'cutoff': 1.5}
            heart: {'trim': 2, 'cutoff': 1.5}
    celltype:
        bypass_intra: False
        plots:
            brain: {'trim': 1, 'cutoff': 1}
